// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVbjLLKs7Sh-A5d0nmBH1wMS2T60qzIo',
    appId: '1:91475247893:web:bd694a15277a6e9222df1c',
    messagingSenderId: '91475247893',
    projectId: 'medical-store-32b5b',
    authDomain: 'medical-store-32b5b.firebaseapp.com',
    storageBucket: 'medical-store-32b5b.appspot.com',
    measurementId: 'G-DHBFLHH72F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK6c91PqrMq_738Ej3TKcZxOk43EMIrNE',
    appId: '1:91475247893:android:4e4bf3c39780a31822df1c',
    messagingSenderId: '91475247893',
    projectId: 'medical-store-32b5b',
    storageBucket: 'medical-store-32b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOoqV4soV8XYD_SH9mUCXz3KmKSQ66E0',
    appId: '1:91475247893:ios:d82d1ddb96ad84fa22df1c',
    messagingSenderId: '91475247893',
    projectId: 'medical-store-32b5b',
    storageBucket: 'medical-store-32b5b.appspot.com',
    iosBundleId: 'com.example.medicalStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOoqV4soV8XYD_SH9mUCXz3KmKSQ66E0',
    appId: '1:91475247893:ios:d82d1ddb96ad84fa22df1c',
    messagingSenderId: '91475247893',
    projectId: 'medical-store-32b5b',
    storageBucket: 'medical-store-32b5b.appspot.com',
    iosBundleId: 'com.example.medicalStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPVbjLLKs7Sh-A5d0nmBH1wMS2T60qzIo',
    appId: '1:91475247893:web:f4426ca6dab34e5022df1c',
    messagingSenderId: '91475247893',
    projectId: 'medical-store-32b5b',
    authDomain: 'medical-store-32b5b.firebaseapp.com',
    storageBucket: 'medical-store-32b5b.appspot.com',
    measurementId: 'G-J8RT3NZJ94',
  );
}
